### ISSUE TITLE
dangerous mutable defaults in List and Choice

### ISSUE THREAD

**Issue by liamhuber** [leon-thomm/ryvencore#24]
On ryvencore 0.3.1.1.

By using mutable defaults, multiple input channels can impact each other. MWE:

```python
import ryvencore as rc

l1 = rc.NodeInputBP(type_='data', dtype=rc.dtypes.List())
l2 = rc.NodeInputBP(type_='data', dtype=rc.dtypes.List())

l2.dtype.val.append('bar')
print(l2.dtype.default, l1.dtype.val, l1.dtype.default)

c1 = rc.NodeInputBP(type_='data', dtype=rc.dtypes.Choice())
c2 = rc.NodeInputBP(type_='data', dtype=rc.dtypes.Choice())

c2.dtype.items.append(str)
print(c1.dtype.items)

>>> ['bar'] ['bar'] ['bar']
>>> [<class 'str'>]
```

If I'm correctly understanding the typical use cases of dtypes, I can't imagine it's very likely someone would come in and mutate things like this, but I guess it's possible someone tries to get clever and update the items available to a choice and winds up updating more choices than they meant to. Adding the pattern `self.items = items if items is not None else []` and changing the signature to `items = None` should clean it up (and similar for `List` and `default`), so even if it's unlikely to be problematic the fix is easy.

**Comment by leon-thomm** [comment]
Thanks a lot, this behavior is definitely unexpected. I just patched v0.3 with bc119da00e6f9506492f4c1063cdeef59b873421, should be available on anaconda very soon.
